import type { Story, Market } from "@/types";
import { generatePriceHistory } from "./price-utils";

const REF = new Date("2026-04-13T12:00:00Z").getTime();

// ─── Politics (7 more, s25-s31) ─────────────────────────────────────

const politicsStories: Story[] = [
  {
    id: "s25", topic: "politics",
    title: "The bipartisan caucus that *meets in a bar basement* every Tuesday",
    summary: "Twelve senators from both parties have been quietly hashing out immigration reform over bourbon since January. No staff. No phones.",
    body: `The meetings started in January, after a particularly bitter floor fight over a spending bill. Senator James Whitfield, a Republican from Tennessee, texted his Democratic colleague Elena Vargas: "We need to stop yelling at each other on camera and start talking off it."\n\nThe location — the basement of a Capitol Hill bar called The Partisan, which everyone involved considers an appropriate irony — was chosen for its lack of cell service. The rule is simple: no staff, no phones, no leaks.\n\nWhat emerged over three months of Tuesday evenings is a framework for immigration reform that neither party's base would design but both might accept. The details remain closely held, but participants describe it as "enforcement plus pathway" — a phrase that would have been politically radioactive five years ago.\n\nWhether the framework survives contact with leadership is another question entirely.`,
    publishedAt: new Date(REF - 7 * 60 * 60 * 1000).toISOString(), marketId: "m25",
  },
  {
    id: "s26", topic: "politics",
    title: "Why the youngest mayor in America is *betting everything on buses*",
    summary: "At 28, she's redirecting 40% of the city's transport budget from roads to bus rapid transit. The recall petition is already circulating.",
    body: `Mayor Priya Desai of Tulsa, Oklahoma was elected on a platform so specific it barely fit on a bumper sticker: bus rapid transit on every major corridor within four years. She is now attempting to deliver on that promise, and the political consequences are arriving faster than the buses.\n\nThe plan redirects $180 million from road widening projects to dedicated bus lanes, electric buses, and redesigned stops with real-time arrival screens. In a city where 94% of commuters drive, the proposal is either visionary or suicidal, depending on who you ask.\n\nDesai's argument is demographic: Tulsa's population is growing, but the growth is concentrated among under-35 residents who are less likely to own cars. "We're building the city for who's arriving," she says, "not who's leaving."\n\nThe recall petition needs 15,000 signatures. Organizers claim to have 11,000.`,
    publishedAt: new Date(REF - 19 * 60 * 60 * 1000).toISOString(), marketId: "m26",
  },
  {
    id: "s27", topic: "politics",
    title: "The amendment nobody noticed could *reshape how America votes*",
    summary: "A one-sentence rider attached to a defense bill would require ranked-choice voting in all federal elections by 2028.",
    body: `Buried on page 1,247 of the National Defense Authorization Act is a provision that has nothing to do with defense. It reads: "All federal elections held after January 1, 2028, shall use ranked-choice voting as the method of determining winners."\n\nThe amendment was introduced by a freshman representative from Maine — the only state that currently uses ranked-choice for federal elections — and was approved in committee without a recorded vote. It is unclear how many members of Congress are aware it exists.\n\nElection law scholars are divided on whether the provision is constitutional. Some argue that Congress has broad authority over federal election procedures. Others note that the method of counting votes has traditionally been a state prerogative.\n\nThe amendment's fate depends on whether it survives conference committee, where differences between House and Senate versions of the bill are reconciled. That process begins next week.`,
    publishedAt: new Date(REF - 33 * 60 * 60 * 1000).toISOString(), marketId: "m27",
  },
  {
    id: "s28", topic: "politics",
    title: "The diplomat who keeps getting *uninvited to summits*",
    summary: "Kenya's UN ambassador has been excluded from three major climate negotiations after publishing leaked transcripts of backroom deals.",
    body: `Ambassador Wanjiku Muthoni has become the most inconvenient diplomat in international climate politics. Over the past year, she has published verbatim transcripts of three closed-door negotiating sessions — each time revealing that wealthy nations were privately agreeing to far less ambitious commitments than they publicly announced.\n\nThe transcripts, posted on the Kenyan mission's official website, caused significant embarrassment. Two sessions were rescheduled after her exclusion. A third proceeded with a new format specifically designed to prevent note-taking.\n\nMuthoni's defense is straightforward: "These are negotiations about the future of every person on Earth. The people those negotiations affect have a right to know what's being said in their name."\n\nHer government has backed her publicly while reportedly asking her to moderate her approach privately. She has declined.`,
    publishedAt: new Date(REF - 41 * 60 * 60 * 1000).toISOString(), marketId: "m28",
  },
  {
    id: "s29", topic: "politics",
    title: "Inside the *algorithmic redistricting* experiment that both parties hate",
    summary: "An independent commission in Arizona handed map-drawing to an algorithm. The results pleased no one — which might be the point.",
    body: `Arizona's Independent Redistricting Commission did something unprecedented this cycle: it fed census data, geographic constraints, and the Voting Rights Act into an open-source algorithm and published the output without human modification.\n\nThe resulting maps are mathematically optimal for compactness, population equality, and minority representation. They are also politically chaotic. Three safe Republican seats became competitive. Two safe Democratic seats did the same. Both parties filed lawsuits within 48 hours.\n\nThe commission's chair, a retired computer science professor, is unbothered. "We asked the algorithm to draw fair maps, not comfortable ones. If every party is equally unhappy, we probably got it right."\n\nThe experiment is being watched nationally. If the maps survive legal challenge, at least four other states have indicated interest in similar approaches.`,
    publishedAt: new Date(REF - 52 * 60 * 60 * 1000).toISOString(), marketId: "m29",
  },
  {
    id: "s30", topic: "politics",
    title: "The Supreme Court case about *a lemonade stand* that could reshape property rights",
    summary: "A 12-year-old's permit dispute has escalated to the highest court. The implications go far beyond citrus.",
    body: `The facts of Hernandez v. City of Austin are almost comically small. A twelve-year-old girl set up a lemonade stand on her family's front lawn. The city issued a cease-and-desist for operating a food business without a permit in a residential zone. Her parents sued.\n\nTwo appellate courts later, the case has become a vehicle for the Supreme Court to reconsider the scope of local zoning authority — a question with implications for everything from home businesses to accessory dwelling units to short-term rentals.\n\nThe petitioners argue that using your own property for small-scale commercial activity is a liberty interest protected by the Fourteenth Amendment. The city argues that zoning is a core police power and that the slippery slope from lemonade to unlicensed restaurants is real.\n\nOral arguments are scheduled for October. The lemonade stand remains closed pending resolution.`,
    publishedAt: new Date(REF - 60 * 60 * 60 * 1000).toISOString(), marketId: "m30",
  },
  {
    id: "s31", topic: "politics",
    title: "Why every presidential candidate is suddenly *talking about sleep*",
    summary: "A viral public health report linked chronic sleep deprivation to $400B in lost productivity. Now it's a campaign issue.",
    body: `The report, published by the CDC in February, was titled "The Sleep Deficit" and ran to 340 pages. Its central finding: Americans averaging less than six hours of sleep per night cost the economy an estimated $411 billion annually in reduced productivity, increased healthcare utilization, and workplace accidents.\n\nWithin weeks, three presidential candidates had incorporated sleep into their platforms. One proposed federally mandated rest breaks for shift workers. Another suggested later school start times as a national standard. A third called for research funding into circadian-aligned work schedules.\n\nCritics call it paternalism. Supporters call it the most cost-effective public health intervention available. The policy details vary, but the political instinct is the same: everyone sleeps, everyone's tired, and telling voters you want to help them rest is surprisingly popular.\n\nPolling suggests that "improving American sleep" tests better than any other health policy proposal among independents.`,
    publishedAt: new Date(REF - 11 * 60 * 60 * 1000).toISOString(), marketId: "m31",
  },
];

// ─── Climate (8 more, s32-s39) ──────────────────────────────────────

const climateStories: Story[] = [
  { id: "s32", topic: "climate", title: "The city that's *paying residents to rip out their lawns*", summary: "Las Vegas is offering $3 per square foot to replace grass with desert landscaping. The water savings are staggering.", body: `Las Vegas has always had an awkward relationship with water. A city of 2.2 million people in the Mojave Desert, it draws nearly all its supply from Lake Mead — a reservoir that has dropped to 35% capacity.\n\nThe city's solution is blunt: pay people to stop watering grass. The "Cash for Grass" program offers $3 per square foot of lawn removed, up to $12,000 per property. In its first year, 14,000 homeowners participated, removing an estimated 40 million square feet of turf.\n\nThe water savings are significant: roughly 9 billion gallons per year, enough to supply 70,000 homes. The program has also had an unexpected aesthetic effect — neighborhoods that were once uniformly green now feature desert gardens with native plants, rock formations, and ironwood trees.\n\nOther Western cities are watching closely. Tucson and Phoenix have launched similar programs, though at lower per-square-foot rates.`, publishedAt: new Date(REF - 13 * 60 * 60 * 1000).toISOString(), marketId: "m32" },
  { id: "s33", topic: "climate", title: "The *carbon-negative concrete* that might actually work", summary: "A Montreal startup claims its cement absorbs more CO2 than it emits. Independent labs are cautiously confirming the numbers.", body: `Concrete is responsible for roughly 8% of global CO2 emissions — more than aviation. Every attempt to decarbonize it has run into the same problem: the chemical reaction that makes cement requires extreme heat, which requires fossil fuels.\n\nCarboNova, a startup spun out of McGill University, claims to have solved this with a process that replaces traditional limestone calcination with a mineralization reaction that actually absorbs CO2 from ambient air during curing. The resulting concrete is, they claim, carbon-negative.\n\nTwo independent labs — one at MIT, one at ETH Zurich — have tested CarboNova's samples and confirmed that the material absorbs approximately 0.1 tons of CO2 per ton produced, compared to the 0.6 tons emitted by conventional concrete. The net effect is genuinely negative.\n\nThe catch is cost: CarboNova's concrete currently costs 2.4x more than conventional. The company argues that carbon pricing and scale will close the gap within five years.`, publishedAt: new Date(REF - 25 * 60 * 60 * 1000).toISOString(), marketId: "m33" },
  { id: "s34", topic: "climate", title: "The ocean current that *shouldn't be slowing down* — but is", summary: "New data shows the Atlantic Meridional Overturning Circulation weakening faster than any model predicted. Scientists are alarmed but not panicking.", body: `The AMOC — the system of ocean currents that carries warm water from the tropics to northern Europe — has been weakening for at least a decade. Climate models predicted this. What they didn't predict was the rate.\n\nNew measurements from an array of sensors spanning the Atlantic at 26°N show that the circulation has weakened by approximately 15% since 2004 — roughly three times faster than the median model projection. The data was published quietly in Nature Geoscience last week.\n\nThe implications are significant but not catastrophic — yet. A weaker AMOC means cooler temperatures in northwestern Europe, altered rainfall patterns in West Africa, and accelerated sea-level rise along the U.S. East Coast.\n\nThe scientific community is being deliberately measured in its public communication. "This is concerning, not apocalyptic," said one of the study's authors. "But it means our models are too conservative, and that should worry everyone."`, publishedAt: new Date(REF - 38 * 60 * 60 * 1000).toISOString(), marketId: "m34" },
  { id: "s35", topic: "climate", title: "The country that *reforested itself* in a single generation", summary: "Costa Rica went from 21% forest cover in 1987 to 60% today. The method was surprisingly simple: pay farmers to grow trees.", body: `In 1987, Costa Rica was losing forest faster than almost any country in the tropics. Cattle ranching and agriculture had reduced forest cover to just 21% — down from over 75% in the 1940s.\n\nThe reversal began with a single policy: Payments for Environmental Services, launched in 1997. The government began paying landowners a per-hectare annual fee to maintain or restore forest on their property. The money came from a fuel tax.\n\nThirty years later, Costa Rica's forest cover stands at approximately 60%. Carbon sequestration from restored forests generates roughly $50 million annually in international carbon credit sales — more than enough to fund the payment program.\n\nThe model has been studied exhaustively and replicated partially in a dozen countries. But few have matched Costa Rica's results, in part because few have matched its political commitment: the program has survived six changes of government without interruption.`, publishedAt: new Date(REF - 50 * 60 * 60 * 1000).toISOString(), marketId: "m35" },
  { id: "s36", topic: "climate", title: "The *floating solar farms* that could power entire coastlines", summary: "China just deployed a 300MW solar array on a flooded coal mine. The irony is not lost on anyone.", body: `The Huainan Solar Farm floats on the surface of a former open-pit coal mine that filled with water after it was abandoned in 2015. At 300 megawatts, it is the largest floating solar installation in the world — and it sits directly above the fuel source it was designed to replace.\n\nFloating solar, or "floatovoltaics," has several advantages over land-based installations. The water cools the panels, increasing efficiency by 5-10%. The panels reduce evaporation from the water surface. And critically, they don't compete with agriculture for land.\n\nChina now has over 2 gigawatts of floating solar capacity, mostly on reservoirs, mining pits, and industrial ponds. India, Japan, and South Korea are scaling rapidly. The global market is projected to reach 60 GW by 2030.\n\nThe technology's limitation is mechanical: waves, wind, and corrosion create maintenance challenges that don't exist on land. But for calm inland water bodies, the economics are already competitive.`, publishedAt: new Date(REF - 55 * 60 * 60 * 1000).toISOString(), marketId: "m36" },
  { id: "s37", topic: "climate", title: "Why *mangrove restoration* is suddenly the hottest investment in carbon markets", summary: "A hectare of mangroves sequesters 4x more carbon than a hectare of rainforest. Investors have noticed.", body: `Mangrove forests occupy a thin strip of coastline in tropical regions — less than 0.1% of the Earth's land surface. But per hectare, they sequester three to four times more carbon than terrestrial forests, mostly in their dense, waterlogged soil.\n\nThis biological fact has made mangrove restoration the fastest-growing category in voluntary carbon markets. In 2025, mangrove-based carbon credits traded at an average of $35 per ton — roughly double the price of standard forestry credits.\n\nThe premium reflects both the carbon math and the co-benefits: mangroves protect coastlines from storms, support fisheries, and filter water. A single restoration project can generate carbon credits, biodiversity credits, and coastal resilience value simultaneously.\n\nSkeptics warn that the rush of capital could lead to low-quality projects or the displacement of coastal communities. "Not every mangrove credit is created equal," cautioned one environmental economist. "The verification standards need to keep pace with the money."`, publishedAt: new Date(REF - 63 * 60 * 60 * 1000).toISOString(), marketId: "m37" },
  { id: "s38", topic: "climate", title: "The *ice core* that rewrote our understanding of ancient climate", summary: "A 3-million-year-old sample from Antarctica shows CO2 levels haven't been this high since before the ice sheet existed.", body: `The Allan Hills Blue Ice area in Antarctica is one of the few places on Earth where ancient ice is pushed to the surface by glacial flow. A team from Princeton University extracted a core from this area that dates to approximately 3 million years ago — the oldest continuous ice sample ever recovered.\n\nThe CO2 levels trapped in that ice tell a striking story: 3 million years ago, atmospheric CO2 was approximately 400 parts per million — essentially identical to today's level. At that concentration, there was no permanent ice sheet in West Antarctica, and sea levels were 15-25 meters higher than today.\n\nThe implication is sobering: the current ice sheet may be living on borrowed time. If CO2 remains at 420+ ppm for centuries, the paleoclimate record suggests that significant ice loss is not a question of if but when.\n\n"The ice is telling us something we don't want to hear," said the study's lead author. "We've already reached the CO2 level that, in the past, was incompatible with the ice sheet we're currently relying on."`, publishedAt: new Date(REF - 70 * 60 * 60 * 1000).toISOString(), marketId: "m38" },
  { id: "s39", topic: "climate", title: "The startup that wants to *dim the sun* — and the scientists who say we should let them try", summary: "Make Sunsets released reflective particles in the stratosphere without permission. The regulatory vacuum is the real story.", body: `Make Sunsets, a startup based in Reno, Nevada, has conducted unauthorized stratospheric aerosol injections on at least four occasions — releasing sulfur dioxide particles at high altitude to reflect a small amount of sunlight back into space.\n\nThe amounts are tiny — equivalent to the emissions of a single commercial flight. The scientific effect is negligible. But the precedent is significant: there are currently no laws, treaties, or regulatory frameworks governing solar geoengineering.\n\nThe scientific community is deeply split. One camp argues that any unilateral geoengineering, however small, sets a dangerous precedent. Another camp — growing in size — argues that the greater danger is failing to research the technique while temperatures continue to rise.\n\n"We're going to need this tool," said a Harvard climate scientist who has spent a decade studying stratospheric aerosols. "The question is whether we develop it carefully through governed research, or recklessly through startups with no oversight."`, publishedAt: new Date(REF - 76 * 60 * 60 * 1000).toISOString(), marketId: "m39" },
];

// ─── Culture (8 more, s40-s47) ──────────────────────────────────────

const cultureStories: Story[] = [
  { id: "s40", topic: "culture", title: "The bookstore that *only sells one book* at a time", summary: "A Tokyo shop displays a single title for two weeks. There's always a line. Publishers are fighting for the slot.", body: `Mori Books occupies a 15-square-meter space in Jimbocho, Tokyo's historic bookselling district. It has one shelf. On that shelf sits one book. Every two weeks, the book changes.\n\nThe concept, created by former publisher Yoshiyuki Morioka, is deliberately absurd in the age of infinite selection. "A bookstore with one book is not a limitation," he says. "It's a recommendation so confident it needs no alternatives."\n\nThe model works because the curation carries weight. Being selected as Mori's book of the fortnight has become one of the most coveted endorsements in Japanese publishing. Sales for chosen titles average 3,000 copies during their two-week run — extraordinary for a single storefront.\n\nMorioka receives approximately 200 submissions per month from publishers. He reads them all. His selection criteria, he says, is simple: "I choose the book I most want to press into someone's hands."`, publishedAt: new Date(REF - 17 * 60 * 60 * 1000).toISOString(), marketId: "m40" },
  { id: "s41", topic: "culture", title: "The orchestra that performs *entirely from memory*", summary: "No sheet music, no conductor's score. The Aurora Orchestra memorizes every note. Critics say it changes the sound completely.", body: `When the Aurora Orchestra performs Beethoven's Fifth, there are no music stands on stage. No printed scores. No conductor waving a baton at a podium. The 45 musicians play the entire 33-minute symphony from memory.\n\nThe practice, which artistic director Nicholas Collon introduced in 2014, has become the ensemble's defining characteristic. "When you remove the paper, something changes in the room," Collon says. "The musicians look at each other. They breathe together. The music becomes a conversation instead of a reading."\n\nCritics have noted a measurable difference in the performances. Eye contact between musicians increases dramatically. Phrasing becomes more spontaneous. Mistakes, paradoxically, decrease — perhaps because the music is more deeply internalized.\n\nThe memorization process takes approximately six weeks of intensive rehearsal. Not every piece survives the translation. "Some music lives on the page," Collon admits. "But the music that survives memorization becomes something else entirely."`, publishedAt: new Date(REF - 29 * 60 * 60 * 1000).toISOString(), marketId: "m41" },
  { id: "s42", topic: "culture", title: "The *font* that's dividing the design world", summary: "A new typeface designed by AI has won three major design awards. Half the industry is celebrating. The other half is furious.", body: `The typeface is called Solis. It was designed — or generated, depending on your perspective — by a system built by a Berlin-based type foundry that fed 12,000 historical typefaces into a neural network and asked it to create something new.\n\nThe result is genuinely beautiful: a humanist sans-serif with subtle optical corrections that most human designers would never think to make. The letterforms have a warmth and rhythm that reviewers have called "uncannily natural."\n\nThe design community's reaction has been predictably polarized. Three major awards — including the Type Directors Club's Certificate of Typographic Excellence — have been awarded to Solis. Several prominent designers have publicly returned their TDC memberships in protest.\n\nThe foundry's creative director is philosophical: "A paintbrush doesn't diminish a painting. A camera didn't kill illustration. The question isn't whether AI was involved — it's whether the typeface is good."`, publishedAt: new Date(REF - 43 * 60 * 60 * 1000).toISOString(), marketId: "m42" },
  { id: "s43", topic: "culture", title: "Why *libraries* are becoming the most important buildings in America", summary: "Library visits are up 31% since 2020. The buildings are evolving into something their founders wouldn't recognize.", body: `The American public library is in the middle of its most significant transformation since Andrew Carnegie started funding them in 1883. Visits are up 31% since 2020. But the people walking through the doors are increasingly there for things other than books.\n\nModern libraries are tax preparation centers, job training hubs, warming shelters, narcan distribution points, ESL classrooms, and mental health resource centers. In some communities, the library is the only public building with free Wi-Fi, air conditioning, and a clean bathroom.\n\nLibrarians are adapting. Many now hold social work credentials. Some carry naloxone. The American Library Association has added "community resilience" to its core competency framework.\n\nThe funding picture is more complicated. Library budgets have not kept pace with their expanding role. "We're being asked to be the social safety net of last resort," said a branch director in Philadelphia, "on a budget designed for book lending."`, publishedAt: new Date(REF - 57 * 60 * 60 * 1000).toISOString(), marketId: "m43" },
  { id: "s44", topic: "culture", title: "The photographer who *only shoots at 4 AM*", summary: "Her images of empty cities have become the defining visual of a generation's insomnia. A retrospective opens next month.", body: `Maren Ishida has been photographing cities between 3:30 and 5:00 AM for eleven years. Not occasionally — every single night. The resulting body of work, over 40,000 images across 60 cities, captures a version of the built environment that most people never see.\n\nThe photographs are eerie but not dark. They show wet streets reflecting neon signs with no one to read them. Open-all-night laundromats with a single dryer spinning. Security guards asleep in lobbies. The light is always strange — a mix of sodium vapor, LED, and the first suggestion of dawn.\n\nCritics have connected her work to the loneliness epidemic, to shift work, to the gig economy's erasure of normal hours. Ishida resists these readings. "I photograph at 4 AM because 4 AM is honest," she says. "There's no performance. The city is just being itself."\n\nA major retrospective opens at the Tate Modern in May.`, publishedAt: new Date(REF - 65 * 60 * 60 * 1000).toISOString(), marketId: "m44" },
  { id: "s45", topic: "culture", title: "The *silence retreat* that costs $15,000 and has a two-year waitlist", summary: "No talking, no screens, no reading. For ten days. In a converted monastery in rural Japan. Applications just reopened.", body: `The Koyasan Silence Retreat occupies a 400-year-old Buddhist monastery on Mount Koya, two hours south of Osaka. For ten days, participants surrender speech, electronic devices, writing instruments, and books. The only permitted activities are walking, eating, sleeping, and sitting.\n\nThe price — $15,000 — covers accommodation, meals, and a private room in the monastery's guest wing. It does not include guidance, instruction, or any form of programming. "We are not offering a meditation retreat," says the retreat's director. "We are offering the absence of everything that prevents you from being alone with yourself."\n\nThe waitlist currently stands at approximately 1,400 people, representing a two-year wait. Participants have included tech executives, professional athletes, one sitting head of state, and — perhaps most tellingly — several therapists.\n\nCompletion rates hover around 70%. Those who leave early almost always do so on day three or four, which staff refer to as "the wall."`, publishedAt: new Date(REF - 72 * 60 * 60 * 1000).toISOString(), marketId: "m45" },
  { id: "s46", topic: "culture", title: "The vinyl record that's *outselling the streaming version* 3 to 1", summary: "An independent artist pressed 50,000 copies of an album with no streaming release. They sold out in hours.", body: `Sable Yoon released her second album, "Terroir," exclusively on vinyl. No Spotify. No Apple Music. No YouTube. No digital release of any kind. The only way to hear it is to buy a physical record.\n\nThe initial pressing of 50,000 copies sold out in four hours. A second pressing of 30,000 sold in six. At $35 per record, the album has grossed over $2.8 million — more than most independent artists earn from streaming in a lifetime.\n\nYoon's explanation is characteristically blunt: "Streaming taught people that music is free. I wanted to make something that costs money, takes up space, and requires your attention. Like a meal, not a snack."\n\nThe music industry is watching with a mixture of admiration and anxiety. If the vinyl-only model works, it works for artists with Yoon's following and cultural cachet. Whether it represents a scalable alternative to streaming is another question entirely.`, publishedAt: new Date(REF - 80 * 60 * 60 * 1000).toISOString(), marketId: "m46" },
  { id: "s47", topic: "culture", title: "The art critic who *rates everything zero or ten*", summary: "No middle ground. No nuance. His binary reviews have become the most read column in contemporary art.", body: `Felix Hauptmann's column in Artforum is titled "Binary." Each month, he reviews five exhibitions. Each receives a score of either 0 or 10. There are no 3s, no 7s, no "mixed but promising" hedges.\n\nThe format, which Hauptmann introduced two years ago, was initially dismissed as a gimmick. It has since become the most-read criticism column in contemporary art, with a newsletter list of over 200,000 subscribers.\n\nHauptmann's argument is philosophical: "The purpose of criticism is to help people decide whether to spend their time. You either need to see this show or you don't. Everything in between is the critic talking about themselves."\n\nArtists dread the zeros. Galleries campaign for the tens. The column has measurably affected attendance — a Hauptmann 10 increases opening-week visitors by an average of 40%, according to one gallery association's data.`, publishedAt: new Date(REF - 85 * 60 * 60 * 1000).toISOString(), marketId: "m47" },
];

// ─── Sports (8 more, s48-s55) ───────────────────────────────────────

const sportsStories: Story[] = [
  { id: "s48", topic: "sports", title: "The basketball player who *practices blindfolded*", summary: "His free throw percentage went from 68% to 94% after six months of shooting without sight. Sports science is scrambling to explain it.", body: `Marcus Webb, a second-year guard for the Memphis Grizzlies, was shooting 68% from the free throw line last November — bad enough that opposing teams were deliberately fouling him. His shooting coach suggested a radical intervention: practice blindfolded.\n\nThe theory, borrowed from motor learning research, is that removing visual feedback forces the body to develop proprioceptive accuracy — a "feel" for the shot that doesn't depend on watching the ball.\n\nSix months later, Webb's free throw percentage sits at 94.2% — third-best in the NBA. More remarkably, his three-point shooting has improved by 11 percentage points despite never practicing threes blindfolded.\n\nSports scientists at the University of Memphis are now studying Webb's case. Early data suggests that blindfolded practice may improve neuromuscular consistency across all shooting motions, not just the practiced one. Three other NBA teams have reportedly begun similar programs.`, publishedAt: new Date(REF - 12 * 60 * 60 * 1000).toISOString(), marketId: "m48" },
  { id: "s49", topic: "sports", title: "The soccer league where *every player is over 60*", summary: "Walking football is the fastest-growing sport in Britain. The average age is 67. The tackles are surprisingly fierce.", body: `Walking football — exactly what it sounds like — has 40,000 registered players in England, making it the country's fastest-growing organized sport. The rules are simple: no running. Anyone who breaks into a jog concedes a free kick.\n\nThe sport was invented in 2011 as a way to keep older adults physically active. It has since developed a competitive structure that its founders never anticipated. There are leagues, cup competitions, and an unofficial world championship.\n\nThe quality of play is higher than outsiders expect. Many participants were serious amateur players in their youth. The absence of speed shifts the game toward positioning, passing, and tactical awareness — skills that don't diminish with age.\n\n"People think it's a joke until they play," says Alan Morrison, 72, captain of the Chesterfield Walking Spireites. "Then they realize they're getting absolutely done by a 68-year-old with better vision than they've ever had."`, publishedAt: new Date(REF - 23 * 60 * 60 * 1000).toISOString(), marketId: "m49" },
  { id: "s50", topic: "sports", title: "Why the *world's best climber* refuses to use a rope", summary: "Alex Honnold's heir apparent is a 22-year-old from the Czech Republic who free solos routes that most professionals won't attempt with full gear.", body: `Adam Ondra was the world's best competitive climber. Now 22-year-old Matěj Novák may be the world's most terrifying one. Novák free solos — climbs without ropes or protection — at a level that even seasoned professionals consider reckless.\n\nHis ascent of "Silence" in Norway's Flatanger cave — a route rated 9c, the hardest in the world — without any protection took the climbing community from admiration to genuine alarm. The route involves upside-down climbing on overhanging rock 60 meters above the ground.\n\n"There's a line between courage and pathology," said one veteran alpinist. "I'm not sure which side of it he's on." Novák's response, delivered with characteristic calm: "Everyone who saw the ascent thought about death. I thought about movement."\n\nSponsors are divided. Two major brands dropped him after the Silence solo. Three others signed him immediately after.`, publishedAt: new Date(REF - 35 * 60 * 60 * 1000).toISOString(), marketId: "m50" },
  { id: "s51", topic: "sports", title: "The *AI umpire* that's better than humans — and why baseball won't use it", summary: "An automated strike zone system got 99.7% of calls right in a minor league trial. The majors still said no.", body: `The Automated Ball-Strike system — known colloquially as "RoboUmp" — completed a full season in the Atlantic League, a minor league affiliated with MLB. Its accuracy rate: 99.7%, compared to approximately 94% for human umpires.\n\nThe technology works: a combination of Hawk-Eye cameras and radar tracks the ball's trajectory through the strike zone with millimeter precision. Calls are delivered to the plate umpire via earpiece in under one second.\n\nMLB has declined to adopt the system for the major leagues, citing "the human element" and player feedback. Several players — particularly pitchers — have expressed a preference for human umpires, whose inconsistencies they have learned to exploit.\n\n"A human ump gives you the low strike if you've been painting corners all night," explained one veteran pitcher. "The robot doesn't care about your body of work." It's a remarkable argument: the system is too fair.`, publishedAt: new Date(REF - 47 * 60 * 60 * 1000).toISOString(), marketId: "m51" },
  { id: "s52", topic: "sports", title: "The swimmer who trained in *a river* and just broke a world record", summary: "She couldn't afford pool time. So she swam in the Ganges at 5 AM. Her 200m backstroke time stunned the world.", body: `Ananya Sharma grew up in Varanasi, on the banks of the Ganges. Her family could not afford pool membership. The nearest competitive pool was 200 kilometers away. So she swam in the river — every morning at 5 AM, navigating currents, boat traffic, and water quality that would alarm most health officials.\n\nAt the Asian Swimming Championships in March, Sharma swam the 200-meter backstroke in 2:03.14 — a world record by 0.6 seconds. The time would have won gold at the last three Olympic Games.\n\nHer coach, a retired physical education teacher who trains her on the riverbank using a whistle and a stopwatch, was characteristically understated: "The river gives you something a pool cannot. It fights you. She learned to swim against resistance that no training program could simulate."\n\nSharma is now training at a proper facility in Bangalore, funded by a government sports scholarship. She misses the river.`, publishedAt: new Date(REF - 53 * 60 * 60 * 1000).toISOString(), marketId: "m52" },
  { id: "s53", topic: "sports", title: "The rugby team that *hasn't lost in three years* — and nobody's watching", summary: "New Zealand's women's sevens team has won 47 consecutive matches. Their average attendance is 2,000.", body: `The New Zealand women's rugby sevens team has not lost a match since April 2023. Forty-seven consecutive victories across World Series events, Olympic qualifiers, and test matches. It is one of the longest winning streaks in any team sport, in any era.\n\nYet average attendance at their home matches hovers around 2,000. Television viewership in New Zealand is a fraction of what the men's All Blacks attract for a single test match. Sponsorship is modest.\n\nThe players are philosophical about the disconnect. "We play for each other," says captain Sarah Hirini, who has 89 caps. "The crowds will come when the culture catches up to what we're doing on the field."\n\nThere are signs of change. A documentary following the team's winning streak has been commissioned by a streaming service. And the NZRU has committed to equal match fees starting next season — a first in the sport's history.`, publishedAt: new Date(REF - 61 * 60 * 60 * 1000).toISOString(), marketId: "m53" },
  { id: "s54", topic: "sports", title: "The marathon that starts at *midnight*", summary: "Ultra-runners in the Sahara are racing 250km across sand dunes in complete darkness. The navigation challenge is the point.", body: `The Nuit du Sahara is a 250-kilometer ultramarathon across the Moroccan desert that begins at midnight and must be completed within 72 hours. Runners carry their own food, water, and navigation equipment. There are no course markings.\n\nThe race was created three years ago by a French adventure sports company as an alternative to the well-known Marathon des Sables. Its distinguishing feature is the darkness: the first 12-15 hours of running take place in complete night, with only headlamps and stars for navigation.\n\nLast year, 34 of 120 starters withdrew — most due to navigation errors that added dozens of extra kilometers. The winner, a former French Foreign Legion soldier named Yann Duchamp, completed the course in 31 hours.\n\n"During the day, you run a race," Duchamp said afterward. "At night, you solve a puzzle. The desert at night is a completely different planet."`, publishedAt: new Date(REF - 69 * 60 * 60 * 1000).toISOString(), marketId: "m54" },
  { id: "s55", topic: "sports", title: "The *esports player* who retired at 23 to become a monk", summary: "He was ranked #1 in League of Legends. Then he shaved his head and moved to a monastery in South Korea. His fans are devastated.", body: `Park "Faker2" Min-jun was, by every measurable metric, the best League of Legends player in the world. His retirement announcement — a two-sentence post on social media — sent shockwaves through an industry worth $1.8 billion.\n\n"I have decided to ordain as a Buddhist monk. Thank you for watching me play." He was 23 years old.\n\nPark now lives at Haeinsa, a 1,200-year-old monastery in South Korea's Gaya Mountains. He rises at 3 AM, meditates for four hours, performs manual labor, and goes to sleep at 9 PM. He has not touched a computer since arriving.\n\nHis former teammates describe the decision as both shocking and, in retrospect, inevitable. "He always said the game was a form of meditation," said one. "I think he just found a better one."`, publishedAt: new Date(REF - 77 * 60 * 60 * 1000).toISOString(), marketId: "m55" },
];

// ─── Tech (6 more, s56-s61) ─────────────────────────────────────────

const techStories: Story[] = [
  { id: "s56", topic: "tech", title: "The database that *forgets on purpose*", summary: "A new architecture deletes data after it's been queried once. Privacy advocates love it. Regulators are confused.", body: `Ephemera is a database designed to self-destruct. Every record stored in it can be read exactly once. After that, it's cryptographically erased — not deleted, not archived, but mathematically destroyed.\n\nThe technology uses a combination of secret sharing and forward secrecy to ensure that once data is retrieved, neither the database operator nor any third party can reconstruct it. The record simply ceases to exist.\n\nThe use cases are narrow but compelling: medical test results that should only be read by the patient, legal discovery documents that must be disclosed but shouldn't persist, whistleblower communications that need plausible destruction.\n\nPrivacy advocates see Ephemera as a foundational tool for a post-GDPR world. Regulators are less enthusiastic. "A database that can't be subpoenaed is either a civil liberties breakthrough or an obstruction of justice tool," said one EU data protection official. "Possibly both."`, publishedAt: new Date(REF - 21 * 60 * 60 * 1000).toISOString(), marketId: "m56" },
  { id: "s57", topic: "tech", title: "Why *mechanical keyboards* are outselling laptops in South Korea", summary: "Custom keyboard culture has gone mainstream. The average enthusiast owns seven boards. The market is worth $2B.", body: `South Korea's custom mechanical keyboard market reached $2.1 billion in 2025, growing 340% in three years. The average enthusiast in a recent survey reported owning 6.8 keyboards, spending an average of $320 per board.\n\nThe hobby, which originated in niche online communities, has been amplified by Korean pop culture. Several K-pop idols have been photographed with custom boards. Keyboard ASMR videos — recordings of typing sounds on different switch types — routinely exceed 10 million views on YouTube.\n\nThe appeal, enthusiasts say, is a combination of aesthetics, tactility, and craft. Building a keyboard from components — switches, keycaps, stabilizers, case, PCB — is a form of industrial design that anyone can practice at a desk.\n\nThe industry has spawned a secondary market for rare keycap sets and vintage switches that rivals sneaker culture in its intensity and pricing. A complete set of "GMK Olivia" keycaps recently sold for $1,200 on the secondary market.`, publishedAt: new Date(REF - 34 * 60 * 60 * 1000).toISOString(), marketId: "m57" },
  { id: "s58", topic: "tech", title: "The *16-year-old* who found a bug in every major browser", summary: "She disclosed responsibly. All four browsers patched within 72 hours. Google offered her a job. She said no.", body: `The vulnerability was in how browsers handle SVG animations — a component so deeply embedded in rendering engines that it affects Chrome, Firefox, Safari, and Edge equally. Exploiting it would allow an attacker to execute arbitrary code through a malicious webpage.\n\nThe discoverer, a 16-year-old from Porto Alegre, Brazil named Luana Ferreira, found the bug while building a personal website. She reported it through each browser's responsible disclosure program and waited patiently for patches.\n\nAll four browsers shipped fixes within 72 hours — an unusually fast response that reflects the severity of the vulnerability. Combined bug bounties totaled approximately $180,000.\n\nGoogle's Chrome security team offered Ferreira an internship. She declined, saying she planned to finish high school first. "I have two more years of math to learn," she told a Brazilian tech magazine. "The bugs will still be there when I'm done."`, publishedAt: new Date(REF - 42 * 60 * 60 * 1000).toISOString(), marketId: "m58" },
  { id: "s59", topic: "tech", title: "The city that replaced its *entire IT department* with open-source software", summary: "Munich's return to Linux after a failed Windows migration is saving €50M per year. Microsoft is not commenting.", body: `Munich's city government completed its migration back to Linux and open-source software in January, three years after reversing a previous controversial decision to adopt Microsoft products. The city's 15,000 workstations now run a custom Linux distribution called LiMux 2.0.\n\nThe cost savings are substantial: approximately €50 million per year in licensing fees, support contracts, and vendor lock-in costs. The migration itself cost €30 million — meaning the project will pay for itself in seven months.\n\nThe technical transition was smoother than the first attempt in 2003, partly because web-based applications have reduced dependency on Windows-specific software. LibreOffice compatibility with Microsoft formats has also improved significantly.\n\nThe political dimension is unavoidable. Munich's original Linux migration was reversed in 2017 after Microsoft relocated its German headquarters to the city. The current government has made digital sovereignty a policy priority.`, publishedAt: new Date(REF - 56 * 60 * 60 * 1000).toISOString(), marketId: "m59" },
  { id: "s60", topic: "tech", title: "The *quantum computer* that just simulated a molecule no classical computer can", summary: "IBM's latest processor solved a chemistry problem in 4 hours that would take a supercomputer 47 years.", body: `IBM's 1,121-qubit Condor processor has achieved what the company calls "quantum advantage in a practical application" — simulating the electronic structure of a nitrogenase enzyme, the protein responsible for biological nitrogen fixation.\n\nThe simulation, which took approximately four hours, would require an estimated 47 years on the world's most powerful classical supercomputer. The result matches experimental observations of nitrogenase behavior, validating the simulation's accuracy.\n\nThe practical significance is enormous. Understanding nitrogenase could lead to synthetic fertilizers that work at room temperature instead of the energy-intensive Haber-Bosch process, which accounts for roughly 2% of global energy consumption.\n\n"This is the first time a quantum computer has told us something about chemistry that we didn't already know," said IBM's head of quantum research. "That's the milestone that matters."`, publishedAt: new Date(REF - 64 * 60 * 60 * 1000).toISOString(), marketId: "m60" },
  { id: "s61", topic: "tech", title: "The operating system built for *a world without internet*", summary: "Designed for rural communities with no connectivity, it syncs via USB drives passed between villages.", body: `KohaOS is an operating system designed for communities with no internet access. Built on a stripped-down Linux kernel, it includes offline versions of Wikipedia, Khan Academy, OpenStreetMap, and a local messaging system — all designed to sync via USB drives physically carried between villages.\n\nThe system was developed by a team at the University of Nairobi and is currently deployed in 230 villages across rural Kenya, Tanzania, and Malawi. Each village has a single solar-powered computer running KohaOS. Once a week, a courier on a motorcycle collects USB drives and distributes updated ones.\n\nThe latency is extreme by modern standards: a message sent from one village takes an average of three days to reach another. But for communities where the alternative is no digital communication at all, the system is transformative.\n\n"We call it the sneakernet," says the project's lead developer. "It's not fast. But it works where nothing else does."`, publishedAt: new Date(REF - 73 * 60 * 60 * 1000).toISOString(), marketId: "m61" },
];

// ─── Economy (4 more, s62-s65) ──────────────────────────────────────

const economyStories: Story[] = [
  { id: "s62", topic: "economy", title: "The company that *pays employees to quit* every year", summary: "Zappos made it famous. Now a Fortune 100 company is offering $50,000 to leave. The ones who stay are worth it.", body: `Every January, Meridian Technologies offers every employee a one-time payment of $50,000 to resign. No strings attached. No re-hire restriction. The check is on the table for two weeks.\n\nLast year, 3.2% of employees took the offer — a number the company considers optimal. "If nobody takes it, the offer isn't high enough," says CEO Diana Cho. "If too many take it, we have a culture problem."\n\nThe economics are counterintuitive but sound. The average cost of a disengaged employee — reduced productivity, negative team effects, eventual turnover costs — is estimated at $85,000 per year. Paying $50,000 for an immediate, clean departure is a bargain by comparison.\n\nThe program's deeper purpose is psychological. Every employee who declines the offer has made an active choice to stay. "We don't want people who are here by inertia," Cho says. "We want people who chose us this year."`, publishedAt: new Date(REF - 27 * 60 * 60 * 1000).toISOString(), marketId: "m62" },
  { id: "s63", topic: "economy", title: "Why *tipping culture* might finally be dying", summary: "Three major restaurant groups eliminated tipping this quarter. Their staff are earning more, not less.", body: `Union Square Hospitality Group, José Andrés's ThinkFoodGroup, and Momofuku have all eliminated tipping across their full portfolio of restaurants in 2026. Menu prices increased 18-22%. Server compensation is now a flat salary plus revenue share.\n\nThe results, six months in, are striking. Average server compensation has increased by approximately 12%. Back-of-house staff — cooks, dishwashers, bussers — have seen increases of 25-30%, as the tip pool that previously favored front-of-house has been replaced by a more equitable distribution.\n\nCustomer satisfaction surveys show no decline. Several metrics improved, including "feeling of welcome" and "overall value." The theory: when servers are paid a salary, they focus on hospitality rather than performance for tips.\n\n"Tipping was always a subsidy from customers to owners," said Danny Meyer of USHG. "We're finally being honest about what things cost."`, publishedAt: new Date(REF - 39 * 60 * 60 * 1000).toISOString(), marketId: "m63" },
  { id: "s64", topic: "economy", title: "The *four-hour workday* experiment that actually worked", summary: "A Swedish hospital tried 6-hour shifts in 2015 and stopped. A tech company just tried 4-hour days. The results are different this time.", body: `Tower26, a 200-person software company in Amsterdam, shifted to four-hour workdays in October 2025. Employees work from 10 AM to 2 PM, Monday through Friday. There are no meetings before 10:30 or after 1:30. Salaries remained unchanged.\n\nSix months later, the company's key metrics have moved in unexpected directions. Revenue per employee increased 14%. Code commits per developer stayed flat. Customer satisfaction scores improved slightly. Voluntary turnover dropped to near zero.\n\nThe company's founder attributes the results to a compression effect: "When you have four hours, you can't waste any of them. Every meeting needs to justify its existence. Every email needs to be necessary."\n\nThe model works partly because Tower26 builds asynchronous software tools — their product philosophy and their work philosophy are aligned. Whether the approach translates to companies with different communication needs remains an open question.`, publishedAt: new Date(REF - 48 * 60 * 60 * 1000).toISOString(), marketId: "m64" },
  { id: "s65", topic: "economy", title: "The *trillion-dollar coin* is back — and this time Congress might actually mint one", summary: "A legal loophole allows the Treasury to mint a platinum coin of any denomination. It's absurd. It might also be necessary.", body: `The United States is approaching another debt ceiling crisis, and the most creative solution on the table is also the most absurd: minting a single platinum coin with a face value of $1 trillion, depositing it at the Federal Reserve, and using the proceeds to fund government operations without issuing new debt.\n\nThe legal basis is real: 31 U.S.C. § 5112(k) gives the Treasury Secretary authority to mint platinum coins of any denomination. The law was intended for commemorative coins. It says nothing about trillion-dollar ones, but it doesn't prohibit them either.\n\nPrevious debt ceiling crises have brought the idea to the edges of serious discussion. This time, three senators have publicly endorsed it as a contingency plan. The Treasury has reportedly prepared a legal memo on the subject.\n\n"It sounds like a joke," said a former Treasury official. "But the alternative — defaulting on U.S. debt — is worse. Sometimes the ridiculous option is the responsible one."`, publishedAt: new Date(REF - 54 * 60 * 60 * 1000).toISOString(), marketId: "m65" },
];

// ─── Science (8 more, s66-s73) ──────────────────────────────────────

const scienceStories: Story[] = [
  { id: "s66", topic: "science", title: "The *mushroom network* that's smarter than we thought", summary: "New research shows fungal networks making decisions, allocating resources, and even learning. The word 'intelligence' is being used carefully.", body: `Mycelial networks — the underground filaments that connect mushrooms and trees — have long been known to transport nutrients. New research from the University of Göttingen suggests they do something more: they make decisions.\n\nIn controlled experiments, fungal networks were presented with multiple food sources of varying quality and distance. The networks consistently allocated more growth toward the higher-quality, closer sources — and they did so faster with repeated exposure, suggesting a form of learning.\n\n"We're not calling it intelligence," says the study's lead author, careful with the terminology. "But it meets several operational definitions of decision-making: information gathering, comparison, and resource allocation based on assessment."\n\nThe findings have implications for agriculture, forestry, and our understanding of what constitutes cognition. If a network without neurons can learn, the definition of intelligence may need to expand.`, publishedAt: new Date(REF - 24 * 60 * 60 * 1000).toISOString(), marketId: "m66" },
  { id: "s67", topic: "science", title: "The *twins study* that's rewriting our understanding of aging", summary: "One twin lived in space for a year. Ten years later, the biological differences between the brothers are growing, not shrinking.", body: `When astronaut Scott Kelly returned from the International Space Station in 2016 after 340 days in space, he was biologically older than his identical twin brother Mark by several measurable metrics. NASA's twin study documented changes in gene expression, telomere length, and immune function.\n\nA follow-up study, published this month, reveals something unexpected: ten years later, many of those differences have not reversed. Some have amplified. Scott's telomeres, which initially shortened and then lengthened in space, are now shorter than Mark's by a statistically significant margin.\n\n"We expected most changes to normalize within a few years," said the study's principal investigator. "The fact that they haven't suggests that spaceflight may have permanent biological consequences we didn't anticipate."\n\nThe finding has significant implications for planned long-duration missions to Mars, where astronauts would spend two to three years in space.`, publishedAt: new Date(REF - 37 * 60 * 60 * 1000).toISOString(), marketId: "m67" },
  { id: "s68", topic: "science", title: "The whale that *sang at the wrong frequency* for 30 years", summary: "Scientists finally found the loneliest whale in the ocean. It wasn't alone after all.", body: `For three decades, a whale in the Pacific Ocean has been tracked by its call — a distinctive 52-hertz tone that falls between the frequencies used by blue whales (10-39 Hz) and fin whales (20 Hz). Because no other whale seems to respond to this frequency, it was dubbed "the loneliest whale in the world."\n\nA research team from Oregon State University has now identified the animal: a blue-fin whale hybrid, photographed and biopsied off the California coast. The biopsy confirmed its hybrid status and revealed something unexpected — it was traveling in the company of two other blue-fin hybrids.\n\n"It was never alone," says the team's lead researcher. "We were just listening for the wrong thing. We heard one call and assumed isolation. In reality, it had companions the whole time — we just couldn't hear them."\n\nThe finding has become an unlikely metaphor in popular culture. The hashtag #52HertzWasNeverAlone trended for three days.`, publishedAt: new Date(REF - 46 * 60 * 60 * 1000).toISOString(), marketId: "m68" },
  { id: "s69", topic: "science", title: "The drug that *reverses gray hair* — with one significant catch", summary: "A clinical trial showed complete hair repigmentation in 67% of participants. But it stops working the moment you stop taking it.", body: `The drug is called melanogenin, and it does exactly what decades of cosmetic science have failed to do: it reverses gray hair. In a Phase II clinical trial of 420 participants, 67% experienced complete or near-complete return of their original hair color within six months.\n\nThe mechanism is straightforward: melanogenin reactivates dormant melanocyte stem cells in hair follicles, restoring the production of melanin pigment. The effect is visible, measurable, and by all accounts genuine.\n\nThe catch is equally straightforward: the effect is entirely dependent on continued use. Within four to six weeks of discontinuation, hair returns to its previous gray state. The drug does not cure aging — it masks one of its symptoms, continuously.\n\nThe pharmaceutical company behind melanogenin has priced it at $200 per month, positioning it as a luxury pharmaceutical. The market for hair color is approximately $30 billion annually. Even capturing a fraction would make melanogenin one of the best-selling drugs in the world.`, publishedAt: new Date(REF - 58 * 60 * 60 * 1000).toISOString(), marketId: "m69" },
  { id: "s70", topic: "science", title: "The *deep-sea creature* that shouldn't exist according to biology textbooks", summary: "Found 8,000 meters down, it photosynthesizes in complete darkness. Nobody can explain how.", body: `The organism, provisionally named Abyssoalgae profundis, was collected at 8,200 meters depth in the Mariana Trench. It is a single-celled eukaryote that contains functional chloroplasts — the organelles responsible for photosynthesis.\n\nThis should be impossible. Photosynthesis requires light. At 8,200 meters, there is no light — not a single photon of sunlight penetrates to that depth. Yet the organism's chloroplasts are active, producing glucose through what appears to be a standard photosynthetic pathway.\n\nThe leading hypothesis, still unconfirmed, is that the organism uses thermal radiation from nearby hydrothermal vents as an energy source for a modified form of photosynthesis. The photons from vent radiation are in the infrared spectrum, far outside the wavelengths used by known photosynthetic organisms.\n\n"If this holds up," said a marine biologist at Woods Hole Oceanographic Institution, "it means we need to revise our definition of photosynthesis. And possibly our definition of where life can exist."`, publishedAt: new Date(REF - 66 * 60 * 60 * 1000).toISOString(), marketId: "m70" },
  { id: "s71", topic: "science", title: "The *asteroid* that's worth more than Earth's entire GDP", summary: "16 Psyche contains an estimated $10 quintillion in metals. NASA's probe arrives next year. The legal questions are fascinating.", body: `16 Psyche is a 226-kilometer-wide asteroid orbiting between Mars and Jupiter. It is composed almost entirely of iron, nickel, and gold. Its estimated value, based on current commodity prices, exceeds $10 quintillion — roughly 100,000 times Earth's annual GDP.\n\nNASA's Psyche probe, launched in 2023, is scheduled to arrive in August 2026. Its mission is scientific: to study the asteroid's composition and determine whether it is the exposed core of a failed protoplanet.\n\nBut the economic and legal implications are already generating debate. The Outer Space Treaty of 1967 prohibits national appropriation of celestial bodies but says nothing about commercial extraction. The 2015 SPACE Act gives U.S. companies the right to own resources they extract from space but doesn't address sovereignty over the source.\n\n"The moment someone can technically mine an asteroid," said a space law professor at Leiden University, "every assumption about resource economics changes. And we have no legal framework ready for it."`, publishedAt: new Date(REF - 74 * 60 * 60 * 1000).toISOString(), marketId: "m71" },
  { id: "s72", topic: "science", title: "The *brain implant* that lets paralyzed patients type by thinking", summary: "Neuralink's competitor just hit 90 words per minute with a thought-to-text interface. The patient cried.", body: `Synchron, the Australian neural interface company, has achieved a milestone: a patient with ALS typed at 90 words per minute using only thought — faster than the average person types on a smartphone keyboard.\n\nThe device, called Stentrode, is implanted through the jugular vein and sits inside a blood vessel in the brain's motor cortex. It reads neural signals associated with intended hand movements and translates them into keystrokes on a computer screen.\n\nThe patient, a 58-year-old former software engineer named David Chen, had been unable to speak or move his hands for three years. His first complete sentence, typed at full speed during a calibration session, was: "I have so much to tell you."\n\nThe neurologist overseeing the trial paused the session. Chen was crying. So was she.\n\nThe technology remains experimental and expensive. But the 90-WPM benchmark crosses a threshold that clinicians consider functionally equivalent to natural communication.`, publishedAt: new Date(REF - 82 * 60 * 60 * 1000).toISOString(), marketId: "m72" },
  { id: "s73", topic: "science", title: "The *CRISPR baby* who just turned seven", summary: "Lulu and Nana, the first gene-edited humans, are healthy and attending school. The ethical debate hasn't aged as well.", body: `In 2018, Chinese scientist He Jiankui edited the genomes of twin embryos to disable the CCR5 gene, which is involved in HIV infection. The twins, known publicly as Lulu and Nana, were born in late 2018. He was imprisoned for three years.\n\nNow seven years old, both children are by all available accounts healthy, developing normally, and attending school in an undisclosed Chinese city. A medical team continues to monitor them, though published data has been minimal.\n\nThe ethical debate that erupted in 2018 has not resolved — if anything, it has deepened. The germline edits will be inherited by Lulu and Nana's future children, making them the first humans whose genetic modifications will propagate through generations.\n\n"The children are fine, and that's wonderful," said a bioethicist at Johns Hopkins. "But 'the children are fine' was never the full argument against what was done. The question was always about consent — and children who inherit edited genes never had the chance to give it."`, publishedAt: new Date(REF - 88 * 60 * 60 * 1000).toISOString(), marketId: "m73" },
];

// ─── Entertainment (9 more, s74-s82) ────────────────────────────────

const entertainmentStories: Story[] = [
  { id: "s74", topic: "entertainment", title: "The TV show that *changes its ending* based on viewer votes", summary: "Each episode has three possible conclusions. Audiences vote in real-time. The results are sometimes surprising.", body: `"Forked Road," a new drama on Netflix, is the first major scripted show to incorporate real-time audience voting into its narrative. Each episode is written with three possible endings. During the final act, viewers vote via the Netflix app. The ending with the most votes airs.\n\nThe production logistics are formidable: all three endings are filmed, scored, and edited before broadcast. The cost is approximately 2.8x a traditional production. Netflix considers it a worthwhile experiment in engagement.\n\nThe results have been surprising. Audiences have consistently chosen the less dramatic, more emotionally nuanced endings — defying the assumption that given a choice, viewers would opt for shock value.\n\n"It turns out people want stories that feel true, not stories that trend," said the show's creator. "The wisdom of the crowd is more literary than we expected."`, publishedAt: new Date(REF - 14 * 60 * 60 * 1000).toISOString(), marketId: "m74" },
  { id: "s75", topic: "entertainment", title: "The stand-up comedian who performs *entirely in silence*", summary: "No words. No sound effects. Just physical comedy for 90 minutes. She just sold out Madison Square Garden.", body: `Nina Conti (no relation to the British ventriloquist of the same name) performs 90 minutes of comedy without uttering a single word. No recorded audio. No musical accompaniment. No signs or cards. Pure physical comedy.\n\nHer show, titled "Quiet," sold out Madison Square Garden in February — 18,000 seats filled for a performer who makes no sound. The reviews were uniformly astonished.\n\nConti's comedy is precise, physical, and surprisingly emotional. She builds scenarios through movement and facial expression that start absurd and end poignant. A recurring bit involving an empty chair has been described by multiple critics as the funniest — and saddest — five minutes in contemporary comedy.\n\n"Words are a shortcut," Conti said in a rare interview (conducted in writing). "When you remove them, you have to be honest with your body. Audiences can feel the difference."`, publishedAt: new Date(REF - 31 * 60 * 60 * 1000).toISOString(), marketId: "m75" },
  { id: "s76", topic: "entertainment", title: "The *AI-generated sitcom* that's actually funny", summary: "Every episode is written, voiced, and animated by AI. The human showrunner's only job is saying 'yes' or 'no.'", body: `"Nothing Special" is a 10-episode animated sitcom on YouTube. Every script was written by an AI system. Every voice was generated. Every frame was animated without human hands. The show has 12 million subscribers.\n\nThe showrunner, former comedy writer Sarah Park, describes her role as "editorial curator." She prompts the AI with a scenario — "two roommates discover their apartment is haunted but can't afford to move" — and the system generates a full 22-minute script with dialogue, staging notes, and visual gags.\n\nPark reviews the output. If she laughs, the episode gets produced. If she doesn't, it's discarded. Her approval rate is approximately 15%.\n\n"The AI generates quantity. I provide quality control," she says. "Eighty-five percent of what it writes is mediocre. But the other fifteen percent is genuinely, surprisingly funny. And that's a better ratio than most writers' rooms."`, publishedAt: new Date(REF - 44 * 60 * 60 * 1000).toISOString(), marketId: "m76" },
  { id: "s77", topic: "entertainment", title: "The movie that was shot *in a single take* over 24 hours", summary: "One camera. No cuts. No rehearsal. The director called it 'cinema as endurance sport.' Critics are divided.", body: `"Daylight" is a 24-hour film shot in a single continuous take with one camera following one character through one day in Buenos Aires. There are no cuts, no montages, and no ellipses. If the character waits for a bus, the audience waits with them.\n\nThe film premiered at the Berlin Film Festival, where it was shown in its entirety — beginning at midnight and ending at midnight the following day. Approximately 200 of the 1,400 audience members remained for the full duration.\n\nCritical response has been polarized. Some call it "the most honest film ever made" and "a radical act of temporal empathy." Others call it "a 24-hour hostage situation with better lighting."\n\nThe director, Argentine filmmaker Lucía Mendoza, expected the debate. "Cinema compresses time. I wanted to see what happens when you refuse to compress. The answer is: boredom, then attention, then something that feels like presence."`, publishedAt: new Date(REF - 51 * 60 * 60 * 1000).toISOString(), marketId: "m77" },
  { id: "s78", topic: "entertainment", title: "The *podcast* that only publishes when the host cries", summary: "A grief counselor records conversations with strangers about loss. Only the episodes that make her cry get released.", body: `"When It Hits" is a podcast hosted by grief counselor Maria Santos. She records long conversations with strangers about loss — of people, places, relationships, identities. The conversations run two to three hours. Only the moments when Santos herself is moved to tears are published.\n\nThe resulting episodes are between 8 and 40 minutes long. They are fragmentary, raw, and frequently devastating. The podcast has 4 million monthly listeners and a 4.9-star rating across platforms.\n\nSantos' editorial principle is personal: "I've been a counselor for twenty years. I don't cry easily. When I do, it means the person has said something universally true — something that anyone, regardless of their specific loss, will recognize."\n\nThe format has drawn criticism from some who argue that a therapist's emotional response shouldn't be the filter for what grief gets published. Santos disagrees: "Everyone's loss is valid. But not every conversation about loss is ready to be heard by millions."`, publishedAt: new Date(REF - 59 * 60 * 60 * 1000).toISOString(), marketId: "m78" },
  { id: "s79", topic: "entertainment", title: "The video game that *deletes itself* if you die", summary: "One life. One copy. If your character dies, the game is permanently erased from your console. It's the best-reviewed game of the year.", body: `"One" is a narrative adventure game with a single, irreversible mechanic: if your character dies, the game uninstalls itself. There are no save points. No extra lives. No reinstallation. You buy the game once, and you either finish it or lose it forever.\n\nThe game costs $60. It takes approximately 12 hours to complete. The average player survives 4.2 hours before death. Completion rate: 6%.\n\nDespite — or because of — these statistics, "One" has become the best-reviewed game of 2026. Critics praise the way permanent death transforms every decision from a game mechanic into a genuine emotional weight.\n\n"I was more careful in this game than I've been in any game in my life," wrote one reviewer. "I moved through the world the way you move through the real one — aware that the next moment isn't guaranteed. That's not a game. That's art."`, publishedAt: new Date(REF - 67 * 60 * 60 * 1000).toISOString(), marketId: "m79" },
  { id: "s80", topic: "entertainment", title: "The album recorded *entirely underwater*", summary: "Hydrophones, modified instruments, and a swimming pool studio. The result sounds like nothing you've heard.", body: `Icelandic musician Ólafur Arnalds recorded his new album "Below" entirely underwater. The sessions took place in a converted geothermal swimming pool in Reykjavik, with musicians performing on modified instruments designed to function when submerged.\n\nThe technical challenges were enormous. Strings needed special coatings. Electronics were sealed in waterproof housings. The musicians wore wetsuits and played in 15-minute intervals between breathing breaks.\n\nThe acoustic result is genuinely novel. Sound travels 4.3 times faster in water than in air, creating a compression effect that makes notes bleed into each other. The album sounds like classical music heard through a dream — familiar forms rendered alien by the medium.\n\n"I wanted to make music that sounds the way water feels," Arnalds said. "Not water sounds — there are plenty of those. I wanted the physics of water to become the composition method itself."`, publishedAt: new Date(REF - 75 * 60 * 60 * 1000).toISOString(), marketId: "m80" },
  { id: "s81", topic: "entertainment", title: "The Broadway show where *the audience is the cast*", summary: "No performers. No script. Just 800 strangers with headphones, following instructions in real-time. It won a Tony.", body: `"Chorus" has no actors. Eight hundred audience members enter the theater, put on wireless headphones, and receive real-time audio instructions from a director sitting in a booth above the stage. "Raise your right hand." "Walk to the person nearest you." "Tell them something true."\n\nOver 90 minutes, the audience — guided by these instructions — creates a performance that is different every night but structurally consistent. The director shapes the crowd like a conductor shapes an orchestra, using timing, repetition, and silence.\n\nThe show won the 2026 Tony Award for Best Special Theatrical Event, making it the first production without professional performers to receive a Tony.\n\n"Theater has always been about the agreement between performer and audience," said the show's creator. "I just removed the distinction."`, publishedAt: new Date(REF - 83 * 60 * 60 * 1000).toISOString(), marketId: "m81" },
  { id: "s82", topic: "entertainment", title: "The streaming service that *only has 12 movies*", summary: "MUBI's radical new tier limits its library to a dozen titles that rotate monthly. Subscribers are watching more, not less.", body: `MUBI, the curated streaming service, launched a new subscription tier called "Twelve." It contains exactly 12 films. When a new one is added, the oldest is removed. There is no search function, no recommendation algorithm, no "continue watching" queue.\n\nThe tier costs the same as the standard subscription ($12.99/month). Within three months, it has attracted 600,000 subscribers — mostly from people who already had the full MUBI library.\n\nThe appeal is counterintuitive: in an era of infinite choice, deliberate scarcity is a relief. Subscribers report spending less time browsing and more time watching. Average completion rates on the Twelve tier are 78%, compared to 34% on the full library.\n\n"Choice is exhausting," said MUBI's CEO. "We already curate. This is curating harder. And it turns out that what people want from a streaming service is not everything — it's someone they trust saying 'watch this.'"`, publishedAt: new Date(REF - 90 * 60 * 60 * 1000).toISOString(), marketId: "m82" },
];

// ─── World (8 more, s83-s90) ────────────────────────────────────────

const worldStories: Story[] = [
  { id: "s83", topic: "world", title: "The village that *banned smartphones* — and got happier", summary: "A 500-person Irish village voted to prohibit smartphones for anyone under 18. Mental health referrals dropped 40%.", body: `Greystones, a coastal village of 500 people in County Wicklow, Ireland, held a public vote in September 2025: should smartphones be prohibited for residents under 18? The measure passed with 71% support.\n\nThe ban is technically voluntary — a social compact rather than a law. But compliance has been near-total. Parents in the community surrendered their children's smartphones and replaced them with basic phones capable of calls and texts.\n\nSix months later, the village GP reports a 40% decline in mental health referrals for adolescents. Teachers report improved concentration and a measurable increase in homework quality. The local GAA club says youth attendance at training has doubled.\n\n"We're not Luddites," says one parent who organized the vote. "We're just asking: what if the phone isn't helping? The data from our village says it wasn't."`, publishedAt: new Date(REF - 16 * 60 * 60 * 1000).toISOString(), marketId: "m83" },
  { id: "s84", topic: "world", title: "The country that just *elected a 31-year-old* prime minister", summary: "Finland already did it. Now Chile has the youngest head of government in the Americas. His first policy: universal basic income.", body: `Matías Ibáñez was inaugurated as Chile's youngest-ever president last month at 31. His first executive action: a universal basic income pilot for the Atacama region, funded by lithium export revenues.\n\nThe policy mirrors proposals that have been tested in Finland, Kenya, and several U.S. cities, but with a distinctive twist: the payment amount is indexed to local cost of living rather than a flat national rate. Residents of mining towns will receive more than residents of Santiago.\n\nIbáñez's election was driven by voters under 35, who turned out at historically unprecedented rates. His campaign was notable for what it didn't promise: no sweeping nationalizations, no confrontation with mining companies, no revolutionary rhetoric. "Boring radicalism," one journalist called it.\n\nThe opposition is cautious rather than hostile. "Let him try," said one conservative senator. "If it works, we'll all claim we supported it."`, publishedAt: new Date(REF - 28 * 60 * 60 * 1000).toISOString(), marketId: "m84" },
  { id: "s85", topic: "world", title: "The *floating city* that just got its first permanent residents", summary: "A 300-person community on modular platforms off the coast of Busan, South Korea, is now officially inhabited.", body: `OCEANIX Busan, the world's first floating city prototype, welcomed its first 50 permanent residents in March. The community occupies three interconnected platforms totaling 6.3 hectares, anchored two kilometers off the coast of Busan, South Korea.\n\nEach platform is designed to be self-sustaining: solar panels and wave energy generators provide power, desalination units produce fresh water, and vertical farms grow a portion of residents' food. Waste is processed on-site.\n\nThe residents — selected from 12,000 applicants — are a mix of researchers, entrepreneurs, and families. Monthly costs are comparable to living in central Busan, subsidized by the project's consortium of backers including UN-Habitat and Samsung.\n\nThe experiment is designed to test whether floating communities can serve as a scalable response to sea-level rise. If the Busan prototype succeeds, larger versions are planned for Bangladesh, the Maldives, and the Marshall Islands.`, publishedAt: new Date(REF - 36 * 60 * 60 * 1000).toISOString(), marketId: "m85" },
  { id: "s86", topic: "world", title: "The *passport* that three countries now accept as valid — but no nation issued", summary: "A digital identity project is creating a stateless passport recognized by Estonia, Singapore, and Paraguay. The UN is watching closely.", body: `The Bitnation World Citizenship passport is not issued by any sovereign nation. It exists as a cryptographic credential on a blockchain, verified by a decentralized network of identity validators. As of this month, three countries — Estonia, Singapore, and Paraguay — accept it as a valid form of identification for certain purposes.\n\nThe acceptance is limited: it works for opening bank accounts and registering businesses, not for visa-free entry. But the symbolism is significant. For the first time, a non-state identity document has been recognized by multiple sovereign governments.\n\nThe project's founder argues that identity should not depend on birth location. "Two billion people worldwide lack recognized identification," she says. "Many of them are stateless, refugees, or victims of administrative failure. We're building an alternative."\n\nCritics worry about accountability: if no state issues the passport, no state is responsible for its misuse.`, publishedAt: new Date(REF - 49 * 60 * 60 * 1000).toISOString(), marketId: "m86" },
  { id: "s87", topic: "world", title: "The African Union just launched *its own GPS system*", summary: "AfriGNSS will provide meter-accurate positioning across the continent. The geopolitical implications are significant.", body: `The African Union officially launched AfriGNSS — the African Global Navigation Satellite System — with the deployment of four initial satellites into medium Earth orbit. When complete, the 24-satellite constellation will provide meter-accurate positioning across the entire African continent.\n\nThe project, funded primarily by the AU's member states with technical support from India and Japan, is designed to reduce the continent's dependence on GPS (American), GLONASS (Russian), Galileo (European), and BeiDou (Chinese).\n\n"Positioning data is sovereignty data," said the project's director. "When your farmers, your military, and your aviation system depend on another nation's satellites, you are dependent in ways that aren't obvious until those satellites are turned off."\n\nThe system will also provide higher accuracy than existing GNSS services in sub-Saharan Africa, where signal availability has historically been worse than in northern latitudes.`, publishedAt: new Date(REF - 62 * 60 * 60 * 1000).toISOString(), marketId: "m87" },
  { id: "s88", topic: "world", title: "The *underground city* that keeps growing beneath Helsinki", summary: "Finland's capital has 10 million square meters of usable space under its streets. Swimming pools, data centers, and a church.", body: `Beneath Helsinki's streets lies a parallel city. Over the past four decades, the Finnish capital has excavated approximately 10 million square meters of underground space — enough to accommodate the entire above-ground footprint of the city center.\n\nThe underground city includes swimming pools, shopping centers, a hockey rink, a church, parking for 10,000 cars, data centers, and an emergency shelter system capable of housing 900,000 people — more than the city's entire population.\n\nThe original motivation was military: during the Cold War, Finland maintained a policy of civil defense preparedness that required extensive underground shelter capacity. The spaces have since been converted to civilian use, creating a second city that operates year-round regardless of weather.\n\n"In a country where winter lasts six months, putting things underground is just common sense," says Helsinki's chief architect. "The question is why more northern cities haven't done the same."`, publishedAt: new Date(REF - 71 * 60 * 60 * 1000).toISOString(), marketId: "m88" },
  { id: "s89", topic: "world", title: "The *refugee camp* that became a city of 400,000 — and wants independence", summary: "Dadaab in Kenya has existed for 32 years. It has hospitals, markets, and a university. Its residents are demanding political recognition.", body: `Dadaab refugee camp in northeastern Kenya was established in 1991 as a temporary settlement for Somalis fleeing civil war. Thirty-two years later, it is home to approximately 400,000 people and has all the infrastructure of a mid-sized city: hospitals, schools, markets, a bus system, and a satellite campus of a Nairobi university.\n\nResidents of Dadaab have begun organizing for political recognition — not as refugees, but as a self-governing community. A council of elected leaders has drafted a charter requesting "autonomous zone" status within Kenya, similar to what some indigenous communities hold in other countries.\n\nThe Kenyan government has not responded officially. The UNHCR has expressed concern that political recognition could set a precedent that discourages host countries from accepting refugees.\n\n"We have been 'temporary' for thirty-two years," said the council's chairperson. "At some point, temporary becomes permanent. We deserve to be governed by people we choose, not managed by agencies we didn't invite."`, publishedAt: new Date(REF - 79 * 60 * 60 * 1000).toISOString(), marketId: "m89" },
  { id: "s90", topic: "world", title: "The bridge connecting two countries that *neither government approved*", summary: "Residents of a border village in Laos and Vietnam built a footbridge with their own money. Customs officials are baffled.", body: `The bridge is 40 meters long, made of steel cable and wooden planks, and spans a narrow stretch of the Mekong River between the village of Pak Beng in Laos and Mường Xén in Vietnam. It was built in three weeks by residents of both villages, funded entirely by private contributions totaling approximately $12,000.\n\nNeither the Lao nor Vietnamese government authorized its construction. There is no customs post, no immigration checkpoint, and no legal framework for cross-border pedestrian traffic at this location.\n\nThe villagers' reasoning is pragmatic: families on both sides of the river are intermarried. The nearest official border crossing is 80 kilometers away. A bridge that takes three minutes to walk was more practical than a four-hour drive.\n\nBorder officials have inspected the bridge and found it structurally sound. The legal question — what to do about an unauthorized international crossing that nobody wants to close — remains unresolved.`, publishedAt: new Date(REF - 86 * 60 * 60 * 1000).toISOString(), marketId: "m90" },
];

export const extraStories: Story[] = [
  ...politicsStories,
  ...climateStories,
  ...cultureStories,
  ...sportsStories,
  ...techStories,
  ...economyStories,
  ...scienceStories,
  ...entertainmentStories,
  ...worldStories,
];

export const extraMarkets: Market[] = [
  // Politics
  { id: "m25", storyId: "s25", question: "Will the bipartisan immigration framework get a floor vote before midterms?", probabilityYes: 0.28, history: generatePriceHistory(0.28), resolvesAt: "2026-11-05T00:00:00Z" },
  { id: "m26", storyId: "s26", question: "Will the Tulsa recall petition reach 15,000 signatures?", probabilityYes: 0.62, history: generatePriceHistory(0.62), resolvesAt: "2026-09-01T00:00:00Z" },
  { id: "m27", storyId: "s27", question: "Will the ranked-choice voting amendment survive conference committee?", probabilityYes: 0.18, history: generatePriceHistory(0.18), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m28", storyId: "s28", question: "Will Ambassador Muthoni be recalled by Kenya's government?", probabilityYes: 0.35, history: generatePriceHistory(0.35), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m29", storyId: "s29", question: "Will Arizona's algorithmic maps survive legal challenge?", probabilityYes: 0.54, history: generatePriceHistory(0.54), resolvesAt: "2027-06-30T00:00:00Z" },
  { id: "m30", storyId: "s30", question: "Will the Supreme Court rule in favor of the lemonade stand?", probabilityYes: 0.46, history: generatePriceHistory(0.46), resolvesAt: "2027-06-30T00:00:00Z" },
  { id: "m31", storyId: "s31", question: "Will any candidate propose a federal sleep policy by September?", probabilityYes: 0.72, history: generatePriceHistory(0.72), resolvesAt: "2026-09-30T00:00:00Z" },
  // Climate
  { id: "m32", storyId: "s32", question: "Will Las Vegas remove 100M sq ft of lawn by 2027?", probabilityYes: 0.58, history: generatePriceHistory(0.58), resolvesAt: "2027-01-01T00:00:00Z" },
  { id: "m33", storyId: "s33", question: "Will CarboNova reach price parity with conventional concrete by 2030?", probabilityYes: 0.32, history: generatePriceHistory(0.32), resolvesAt: "2030-01-01T00:00:00Z" },
  { id: "m34", storyId: "s34", question: "Will AMOC weaken another 5% by 2028?", probabilityYes: 0.45, history: generatePriceHistory(0.45), resolvesAt: "2028-01-01T00:00:00Z" },
  { id: "m35", storyId: "s35", question: "Will three more countries adopt Costa Rica's payment model by 2028?", probabilityYes: 0.41, history: generatePriceHistory(0.41), resolvesAt: "2028-01-01T00:00:00Z" },
  { id: "m36", storyId: "s36", question: "Will global floating solar exceed 20 GW by 2028?", probabilityYes: 0.67, history: generatePriceHistory(0.67), resolvesAt: "2028-01-01T00:00:00Z" },
  { id: "m37", storyId: "s37", question: "Will mangrove credits exceed $50/ton by year-end?", probabilityYes: 0.39, history: generatePriceHistory(0.39), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m38", storyId: "s38", question: "Will the Allan Hills ice core finding be replicated by another team?", probabilityYes: 0.71, history: generatePriceHistory(0.71), resolvesAt: "2027-12-31T00:00:00Z" },
  { id: "m39", storyId: "s39", question: "Will a solar geoengineering regulatory framework exist by 2028?", probabilityYes: 0.24, history: generatePriceHistory(0.24), resolvesAt: "2028-01-01T00:00:00Z" },
  // Culture
  { id: "m40", storyId: "s40", question: "Will a Mori Books pick sell over 10,000 copies in its two-week window?", probabilityYes: 0.38, history: generatePriceHistory(0.38), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m41", storyId: "s41", question: "Will the Aurora Orchestra perform a full Mahler symphony from memory?", probabilityYes: 0.27, history: generatePriceHistory(0.27), resolvesAt: "2027-06-30T00:00:00Z" },
  { id: "m42", storyId: "s42", question: "Will an AI-designed typeface win the TDC award again next year?", probabilityYes: 0.52, history: generatePriceHistory(0.52), resolvesAt: "2027-03-31T00:00:00Z" },
  { id: "m43", storyId: "s43", question: "Will US library funding increase by 10%+ in the next federal budget?", probabilityYes: 0.22, history: generatePriceHistory(0.22), resolvesAt: "2026-10-01T00:00:00Z" },
  { id: "m44", storyId: "s44", question: "Will Ishida's retrospective set a Tate Modern attendance record?", probabilityYes: 0.34, history: generatePriceHistory(0.34), resolvesAt: "2026-08-31T00:00:00Z" },
  { id: "m45", storyId: "s45", question: "Will a competing silence retreat open in the US by year-end?", probabilityYes: 0.61, history: generatePriceHistory(0.61), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m46", storyId: "s46", question: "Will another major artist release a vinyl-only album this year?", probabilityYes: 0.55, history: generatePriceHistory(0.55), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m47", storyId: "s47", question: "Will Hauptmann give more 10s than 0s this year?", probabilityYes: 0.43, history: generatePriceHistory(0.43), resolvesAt: "2026-12-31T00:00:00Z" },
  // Sports
  { id: "m48", storyId: "s48", question: "Will Webb finish the season above 90% from the line?", probabilityYes: 0.73, history: generatePriceHistory(0.73), resolvesAt: "2026-06-30T00:00:00Z" },
  { id: "m49", storyId: "s49", question: "Will walking football reach 100,000 registered players in England?", probabilityYes: 0.56, history: generatePriceHistory(0.56), resolvesAt: "2027-01-01T00:00:00Z" },
  { id: "m50", storyId: "s50", question: "Will Novák free solo another 9c route this year?", probabilityYes: 0.41, history: generatePriceHistory(0.41), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m51", storyId: "s51", question: "Will MLB adopt automated strike zones by 2028?", probabilityYes: 0.37, history: generatePriceHistory(0.37), resolvesAt: "2028-04-01T00:00:00Z" },
  { id: "m52", storyId: "s52", question: "Will Sharma medal at the 2028 Olympics?", probabilityYes: 0.48, history: generatePriceHistory(0.48), resolvesAt: "2028-08-15T00:00:00Z" },
  { id: "m53", storyId: "s53", question: "Will NZ women's sevens reach 60 consecutive wins?", probabilityYes: 0.63, history: generatePriceHistory(0.63), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m54", storyId: "s54", question: "Will the Nuit du Sahara completion rate exceed 50% this year?", probabilityYes: 0.19, history: generatePriceHistory(0.19), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m55", storyId: "s55", question: "Will Park return to competitive gaming within 2 years?", probabilityYes: 0.15, history: generatePriceHistory(0.15), resolvesAt: "2028-04-14T00:00:00Z" },
  // Tech
  { id: "m56", storyId: "s56", question: "Will Ephemera be banned in any EU country by year-end?", probabilityYes: 0.33, history: generatePriceHistory(0.33), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m57", storyId: "s57", question: "Will the custom keyboard market exceed $3B globally in 2027?", probabilityYes: 0.58, history: generatePriceHistory(0.58), resolvesAt: "2027-12-31T00:00:00Z" },
  { id: "m58", storyId: "s58", question: "Will Ferreira accept an internship at a major tech company before 18?", probabilityYes: 0.29, history: generatePriceHistory(0.29), resolvesAt: "2027-12-31T00:00:00Z" },
  { id: "m59", storyId: "s59", question: "Will another major European city announce a Linux migration in 2026?", probabilityYes: 0.42, history: generatePriceHistory(0.42), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m60", storyId: "s60", question: "Will quantum advantage be demonstrated in drug discovery by 2028?", probabilityYes: 0.51, history: generatePriceHistory(0.51), resolvesAt: "2028-01-01T00:00:00Z" },
  { id: "m61", storyId: "s61", question: "Will KohaOS reach 1,000 villages by year-end?", probabilityYes: 0.44, history: generatePriceHistory(0.44), resolvesAt: "2026-12-31T00:00:00Z" },
  // Economy
  { id: "m62", storyId: "s62", question: "Will a second Fortune 100 company adopt a pay-to-quit program?", probabilityYes: 0.47, history: generatePriceHistory(0.47), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m63", storyId: "s63", question: "Will tipping be eliminated at 50+ major US restaurant locations by year-end?", probabilityYes: 0.53, history: generatePriceHistory(0.53), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m64", storyId: "s64", question: "Will Tower26's revenue per employee remain above pre-change levels?", probabilityYes: 0.66, history: generatePriceHistory(0.66), resolvesAt: "2027-04-01T00:00:00Z" },
  { id: "m65", storyId: "s65", question: "Will the US mint a trillion-dollar coin to avoid default?", probabilityYes: 0.08, history: generatePriceHistory(0.08), resolvesAt: "2026-09-30T00:00:00Z" },
  // Science
  { id: "m66", storyId: "s66", question: "Will fungal 'intelligence' be confirmed by independent replication?", probabilityYes: 0.62, history: generatePriceHistory(0.62), resolvesAt: "2027-06-30T00:00:00Z" },
  { id: "m67", storyId: "s67", question: "Will NASA revise Mars mission duration guidelines based on the twins study?", probabilityYes: 0.38, history: generatePriceHistory(0.38), resolvesAt: "2027-12-31T00:00:00Z" },
  { id: "m68", storyId: "s68", question: "Will more blue-fin whale hybrids be identified in the Pacific?", probabilityYes: 0.71, history: generatePriceHistory(0.71), resolvesAt: "2027-06-30T00:00:00Z" },
  { id: "m69", storyId: "s69", question: "Will melanogenin reach Phase III trials by year-end?", probabilityYes: 0.55, history: generatePriceHistory(0.55), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m70", storyId: "s70", question: "Will infrared photosynthesis be confirmed by a second team?", probabilityYes: 0.34, history: generatePriceHistory(0.34), resolvesAt: "2027-12-31T00:00:00Z" },
  { id: "m71", storyId: "s71", question: "Will NASA's Psyche probe find gold concentrations above predictions?", probabilityYes: 0.42, history: generatePriceHistory(0.42), resolvesAt: "2027-06-30T00:00:00Z" },
  { id: "m72", storyId: "s72", question: "Will thought-to-text exceed 120 WPM within two years?", probabilityYes: 0.47, history: generatePriceHistory(0.47), resolvesAt: "2028-04-14T00:00:00Z" },
  { id: "m73", storyId: "s73", question: "Will any country legalize germline gene editing by 2030?", probabilityYes: 0.26, history: generatePriceHistory(0.26), resolvesAt: "2030-01-01T00:00:00Z" },
  // Entertainment
  { id: "m74", storyId: "s74", question: "Will 'Forked Road' be renewed for a second season?", probabilityYes: 0.78, history: generatePriceHistory(0.78), resolvesAt: "2026-09-30T00:00:00Z" },
  { id: "m75", storyId: "s75", question: "Will the silent comedy show gross $10M+ in ticket sales?", probabilityYes: 0.64, history: generatePriceHistory(0.64), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m76", storyId: "s76", question: "Will 'Nothing Special' exceed 20M YouTube subscribers?", probabilityYes: 0.57, history: generatePriceHistory(0.57), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m77", storyId: "s77", question: "Will 'Daylight' win any major film festival award?", probabilityYes: 0.31, history: generatePriceHistory(0.31), resolvesAt: "2027-03-31T00:00:00Z" },
  { id: "m78", storyId: "s78", question: "Will 'When It Hits' reach 10M monthly listeners?", probabilityYes: 0.52, history: generatePriceHistory(0.52), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m79", storyId: "s79", question: "Will 'One' sell more than 5 million copies?", probabilityYes: 0.44, history: generatePriceHistory(0.44), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m80", storyId: "s80", question: "Will 'Below' be nominated for a Grammy?", probabilityYes: 0.36, history: generatePriceHistory(0.36), resolvesAt: "2027-02-28T00:00:00Z" },
  { id: "m81", storyId: "s81", question: "Will 'Chorus' run for more than one year on Broadway?", probabilityYes: 0.68, history: generatePriceHistory(0.68), resolvesAt: "2027-06-30T00:00:00Z" },
  { id: "m82", storyId: "s82", question: "Will MUBI's Twelve tier reach 1M subscribers?", probabilityYes: 0.59, history: generatePriceHistory(0.59), resolvesAt: "2026-12-31T00:00:00Z" },
  // World
  { id: "m83", storyId: "s83", question: "Will three more Irish villages adopt smartphone bans?", probabilityYes: 0.65, history: generatePriceHistory(0.65), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m84", storyId: "s84", question: "Will Chile's UBI pilot show positive employment effects?", probabilityYes: 0.54, history: generatePriceHistory(0.54), resolvesAt: "2027-06-30T00:00:00Z" },
  { id: "m85", storyId: "s85", question: "Will OCEANIX Busan reach 200 residents by year-end?", probabilityYes: 0.48, history: generatePriceHistory(0.48), resolvesAt: "2026-12-31T00:00:00Z" },
  { id: "m86", storyId: "s86", question: "Will a fourth country recognize the Bitnation passport?", probabilityYes: 0.37, history: generatePriceHistory(0.37), resolvesAt: "2027-06-30T00:00:00Z" },
  { id: "m87", storyId: "s87", question: "Will AfriGNSS reach 12 operational satellites by 2028?", probabilityYes: 0.52, history: generatePriceHistory(0.52), resolvesAt: "2028-01-01T00:00:00Z" },
  { id: "m88", storyId: "s88", question: "Will another Nordic city begin a major underground expansion?", probabilityYes: 0.43, history: generatePriceHistory(0.43), resolvesAt: "2027-12-31T00:00:00Z" },
  { id: "m89", storyId: "s89", question: "Will Dadaab receive any form of political recognition by 2028?", probabilityYes: 0.21, history: generatePriceHistory(0.21), resolvesAt: "2028-01-01T00:00:00Z" },
  { id: "m90", storyId: "s90", question: "Will the unauthorized bridge remain open for a full year?", probabilityYes: 0.73, history: generatePriceHistory(0.73), resolvesAt: "2027-04-14T00:00:00Z" },
];
